# Paths to the MEG data, Freesurfer subjects directory, and metadata directory
study: "LPPDistraction2024"
task: "distraction"
session: ""
meg_dir: "meg"
base_path: "/neurospin/unicog/protocols/IRMf/LePetitPrince_Pallier_2018/MEG/workspace-LPP/data/MEG/LPP/"
subjects_dir: "LPP_MEG_auditory/derivatives/freesurfer/"
metadata: "/home_local/Bonnaire/metadata/"
cross_talk_file: "calibration_MEG/old_MEG/ct_sparse_nspn.fif"
calibration_file: "calibration_MEG/old_MEG/sss_cal_nspn.dat"

# Preprocessing parameters
num_threads: 1
middle_run: "run-05"
filter_low: 0.5
filter_high: 20
epoch_tmin: -0.500
epoch_tmax: 0.800
baseline: [-0.500, 0]

# Run settings
runs: [1, 2, 3, 4, 5, 6, 7, 8, 9]

# Matching tolerances
tolerances:
  (9, 6): [30, 5]
  (10, 6): [30, 5]
  (12, 5): [30, 5]
  (13, 3): [5, 30]
  (13, 7): [5, 30]
  (14, 9): [30, 5]
  (21, 6): [200, 5]
  (21, 8): [30, 5]
  (22, 4): [30, 5]
  (33, 2): [40, 40]
  (39, 5): [45, 5]
  (40, 2): [80, 5]
  (41, 1): [40, 5]
  (43, 4): [200, 5]
  (43, 5): [110, 5]
  (44, 9): [30, 5]
  (24, 2): [10, 20]